---Find Total Customers by countries
SELECT country, COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC

---Find Total Customers by Gender
SELECT gender, COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC

---FInd Total Products by Category
SELECT category, COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC

---What is Ag cost in each category
SELECT category, AVG(cost) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC

---What is total revenue generated by each category
SELECT p.category, SUM(f.price) AS revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON f.product_key = p.product_key
GROUP BY p.category
ORDER BY revenue DESC

---What is total revenue generated by each customer
SELECT c.customer_id, c.first_name, c.last_name ,SUM(f.price) AS revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON f.customer_key = c.customer_key
GROUP BY c.customer_id, c.first_name, c.last_name
ORDER BY SUM(f.price) DESC
  
  ---What is distribution of sold items across countries
SELECT c.country, SUM(f.quantity) AS total_items_ordered
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON f.customer_key = c.customer_key
GROUP BY c.country
ORDER BY COUNT(f.quantity) DESC

---Which 5 products generate the highest revenue
SELECT TOP 5 p.product_name, SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY total_revenue DESC

SELECT *
FROM(
    SELECT p.product_name,
           SUM(f.sales_amount) AS total_sales,
           ROW_NUMBER() OVER (ORDER BY SUM(f.sales_amount) DESC) AS product_rank
    FROM gold.fact_sales f
    LEFT JOIN gold.dim_products p
    ON p.product_key = f.product_key
    GROUP BY p.product_name
    )t
WHERE product_rank <= 5

---What are 5 worst performing products in terms of sales
SELECT TOP 5 p.product_name, SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY total_revenue 
